import type { ScoopdReport, AccountSnapshot } from "../types.js";

export function formatReportMarkdown(report: ScoopdReport, handle: string): string {
  const lines: string[] = [];

  lines.push(`# Competitor Intelligence Report: @${handle}`, "");

  if (report.snapshot) {
    const s = report.snapshot;
    lines.push("## Account Snapshot");
    lines.push(`- **Followers**: ${s.followers?.toLocaleString() ?? "N/A"}`);
    lines.push(`- **Following**: ${s.following?.toLocaleString() ?? "N/A"}`);
    lines.push(`- **Posts**: ${s.total_posts?.toLocaleString() ?? "N/A"}`);
    lines.push(`- **Avg Likes**: ${s.avg_likes?.toLocaleString() ?? "N/A"}`);
    lines.push(`- **Avg Comments**: ${s.avg_comments?.toLocaleString() ?? "N/A"}`);
    lines.push(`- **Engagement Rate**: ${s.engagement_rate ? (s.engagement_rate * 100).toFixed(2) + "%" : "N/A"}`);
    lines.push(`- **Niche**: ${s.niche ?? "N/A"}`);
    if (s.bio) lines.push(`- **Bio**: ${s.bio}`);
    lines.push("");
  }

  if (report.content_dna) {
    const d = report.content_dna;
    lines.push("## Content DNA");
    if (d.topics?.length) lines.push(`- **Topics**: ${d.topics.join(", ")}`);
    if (d.formats?.length) lines.push(`- **Formats**: ${d.formats.join(", ")}`);
    if (d.content_pillars?.length) lines.push(`- **Content Pillars**: ${d.content_pillars.join(", ")}`);
    lines.push(`- **Avg Length**: ${d.avg_length_seconds ?? "N/A"}s`);
    lines.push(`- **Posting Frequency**: ${d.posting_frequency ?? "N/A"}`);
    lines.push("");
  }

  if (report.hooks) {
    lines.push("## Hook Analysis");
    for (const hook of report.hooks.hooks ?? []) {
      lines.push(`- **"${hook.text}"** (${hook.type}) — ${hook.effectiveness}`);
    }
    lines.push("");
  }

  if (report.gaps) {
    lines.push("## Gap & Opportunity Analysis");
    for (const gap of report.gaps.gaps ?? []) {
      lines.push(`### ${gap.area}`);
      lines.push(`- ${gap.description}`);
      lines.push(`- **Opportunity**: ${gap.opportunity}`);
    }
    lines.push("");
  }

  if (report.sentiment) {
    lines.push("## Sentiment Analysis");
    lines.push(`- **Tone**: ${report.sentiment.overall_tone}`);
    lines.push(`- **Community**: ${report.sentiment.community_strength}`);
    if (report.sentiment.themes?.length) {
      lines.push(`- **Themes**: ${report.sentiment.themes.join(", ")}`);
    }
    lines.push("");
  }

  if (report.hashtags) {
    lines.push("## Hashtag Strategy");
    lines.push(`- **Avg per post**: ${report.hashtags.avg_per_post}`);
    if (report.hashtags.top_hashtags?.length) {
      lines.push(`- **Top**: ${report.hashtags.top_hashtags.join(", ")}`);
    }
    if (report.hashtags.recommended?.length) {
      lines.push(`- **Recommended**: ${report.hashtags.recommended.join(", ")}`);
    }
    lines.push("");
  }

  if (report.top_performers) {
    lines.push("## Top Performing Reels");
    for (const reel of report.top_performers.reels ?? []) {
      lines.push(`- **ER ${(reel.engagement_rate * 100).toFixed(1)}%**: "${reel.caption}"`);
      lines.push(`  - Why: ${reel.why_it_worked}`);
    }
    lines.push("");
  }

  if (report.brand_voice) {
    lines.push("## Brand Voice Profile");
    lines.push(`- **Personality**: ${report.brand_voice.personality}`);
    lines.push(`- **Tone**: ${report.brand_voice.tone_spectrum}`);
    if (report.brand_voice.signature_phrases?.length) {
      lines.push(`- **Signature Phrases**: ${report.brand_voice.signature_phrases.join(", ")}`);
    }
    lines.push(`- **CTA Style**: ${report.brand_voice.cta_style}`);
    lines.push("");
  }

  if (report.posting_patterns) {
    lines.push("## Posting Patterns");
    lines.push(`- **Best Day**: ${report.posting_patterns.best_day}`);
    lines.push(`- **Worst Day**: ${report.posting_patterns.worst_day}`);
    lines.push(`- **Consistency**: ${report.posting_patterns.consistency_score}/10`);
    lines.push("");
  }

  lines.push("---");
  lines.push("*Generated by [Scoopd](https://scoopd.pro) — AI-powered competitor intelligence*");

  return lines.join("\n");
}
